### ISSUE TITLE
Harvesting Leaves with Shears does not drop the Leaves

### ISSUE THREAD

**Issue by NillerMedDild** [Vazkii/Botania#3275]
# Version Information
Forge version:  1.14.4-28.2.4
Botania version:  Botania r1.11-379

# Further Information
Link to crash log: (please use a paste site such as [gist](https://gist.github.com/), do not attach the .txt or paste the log inline)\
Steps to reproduce:
1. Obtain Manasteel Shears
2. Harvest Leaves with them.
3. Observe that no leaves drop.

What I expected to happen:
For leaves to drop.

What happened instead:
They did not.

**Comment by Killako** [comment]
Fixed in Botania r1.15-383, update Botania. See #3262

**Comment by Killako** [comment]
Fixed in Botania r1.15-383. See #3262

**Comment by NillerMedDild** [comment]
Ah damn, I somehow didn't find that issue. Do you plan to fix this for 1.14, or not so much? :)

**Comment by elowanut** [comment]
Forge version: forge-1.15.2-31.1.74
Botania version: Botania-r1.15-383
Other versions: curios-FORGE-1.15.2-2.0.2.2, Patchouli-1.15.2-1.2-33

Unfortunately, as far as I can tell, the merges related to the shears tagging etc.. did not fix this problem in 1.15.2, either. As of the most current versions, and isolated by itself (e.g. just Forge, Botania, Curios, Patchouli), regular shears work normally, manasteel and elementium shears only shear sheep.

**Comment by williewillus** [comment]
that's completely on forge, which has still not merged a shears tag and overrides for the vanilla loot tables to check said tag. nothing we can do anymore besides bug them to add it.

**Comment by NillerMedDild** [comment]
Good to know, thanks.

**Comment by WebDragon** [comment]
am still experiencing this issue on Botania-r1.15-384.jar, where they do not work with leaves, grass, or beehives. did 383-384 regress, or is it still not quite yet all the way fixed ?

**Comment by elowanut** [comment]
Forge has been mucking around with the shears tag (see [this Forge pull](https://github.com/MinecraftForge/MinecraftForge/pull/6765)) and the way loot tables are provided.

The current state of things is that botania shears will give you drops with tall grasses, but not with regular grasses and not with leaves.

**Comment by Hubry** [comment]
Everything is working properly on 1.16 builds now, closing this.
