### ISSUE TITLE
Crashes with Create's ponder UI.

### ISSUE THREAD

**Issue by Rileybutt** [Vazkii/Botania#3988]
### Mod Loader

Forge

### Minecraft Version

1.18.1

### Botania version

1.18.1-429

### Modloader version

Forge-1.18.1-39.0.88

### The latest.log file

https://gist.github.com/Rileybutt/aacde6769bbf7d8d3ae48d8a28bfc796

### Issue description

I am running a custom mod pack that contains Botania and Create. I was running version 428 of Botania previously and was getting crashes with Create's ponder screen until I came on to the issues page here and saw that it was fixed in Botania-429. I updated my mods with the new version of Botania but the crash is still present even in the newer version.

Here is the crash report the game gave me after the most recent pondering crash:
https://gist.github.com/Rileybutt/775a5c98c2e992e173555c047bc3f93f

### Steps to reproduce

1. Install Botania and Create into Minecraft.
2. Grab an item from Create that processes or uses items (ie. Mill, Crushing Wheel, Deployer).
3. Hold W (or other keybind) on the item to open the Ponder screen.
4. Wait for an item (the wheat for the Mill, for example) to fall or spawn onto the screen and interact with the block/item in question.
5. The game instantly freezes and crashes.

**Comment by williewillus** [comment]
fixed in next release

**Comment by Rileybutt** [comment]
Oh, sorry if I wasn't clear. I am on release 429 which is listed as the newest release on Curseforge. I cannot find a newer release anywhere. I might not of been clear though. I WAS on release 428. I upgraded to release 429, the next release and the bug is still present.
